pipeline {

    agent any
    
    environment {
        PASS = credentials('registry-pass') 
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./jenkins/pipeline/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./jenkins/build/build.sh

                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'jenkins/pipeline/java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/pipeline/jenkins/test/mvn.sh mvn test'
            }

            post {
                always {
                    junit 'jenkins/pipeline/java-app/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './jenkins/pipeline/jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './jenkins/pipeline/jenkins/deploy/deploy.sh'
            }
        }
    }
}
